// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Metric_Gauge
	//	*Metric_Counter
	Value         isMetric_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_proto_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetValue() isMetric_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Metric) GetGauge() *Gauge {
	if x != nil {
		if x, ok := x.Value.(*Metric_Gauge); ok {
			return x.Gauge
		}
	}
	return nil
}

func (x *Metric) GetCounter() *Counter {
	if x != nil {
		if x, ok := x.Value.(*Metric_Counter); ok {
			return x.Counter
		}
	}
	return nil
}

type isMetric_Value interface {
	isMetric_Value()
}

type Metric_Gauge struct {
	Gauge *Gauge `protobuf:"bytes,2,opt,name=gauge,proto3,oneof"`
}

type Metric_Counter struct {
	Counter *Counter `protobuf:"bytes,3,opt,name=counter,proto3,oneof"`
}

func (*Metric_Gauge) isMetric_Value() {}

func (*Metric_Counter) isMetric_Value() {}

type Gauge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gauge) Reset() {
	*x = Gauge{}
	mi := &file_proto_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gauge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gauge) ProtoMessage() {}

func (x *Gauge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gauge.ProtoReflect.Descriptor instead.
func (*Gauge) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *Gauge) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Counter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         int64                  `protobuf:"varint,1,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Counter) Reset() {
	*x = Counter{}
	mi := &file_proto_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counter) ProtoMessage() {}

func (x *Counter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counter.ProtoReflect.Descriptor instead.
func (*Counter) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *Counter) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type MetricRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MetricRequest_Metric
	//	*MetricRequest_Data
	Payload       isMetricRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricRequest) Reset() {
	*x = MetricRequest{}
	mi := &file_proto_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRequest) ProtoMessage() {}

func (x *MetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRequest.ProtoReflect.Descriptor instead.
func (*MetricRequest) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *MetricRequest) GetPayload() isMetricRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MetricRequest) GetMetric() *Metric {
	if x != nil {
		if x, ok := x.Payload.(*MetricRequest_Metric); ok {
			return x.Metric
		}
	}
	return nil
}

func (x *MetricRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*MetricRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isMetricRequest_Payload interface {
	isMetricRequest_Payload()
}

type MetricRequest_Metric struct {
	Metric *Metric `protobuf:"bytes,1,opt,name=metric,proto3,oneof"`
}

type MetricRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*MetricRequest_Metric) isMetricRequest_Payload() {}

func (*MetricRequest_Data) isMetricRequest_Payload() {}

type BulkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BulkRequest_Metrics
	//	*BulkRequest_Data
	Payload       isBulkRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkRequest) Reset() {
	*x = BulkRequest{}
	mi := &file_proto_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkRequest) ProtoMessage() {}

func (x *BulkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkRequest.ProtoReflect.Descriptor instead.
func (*BulkRequest) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *BulkRequest) GetPayload() isBulkRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BulkRequest) GetMetrics() *Metrics {
	if x != nil {
		if x, ok := x.Payload.(*BulkRequest_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *BulkRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*BulkRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isBulkRequest_Payload interface {
	isBulkRequest_Payload()
}

type BulkRequest_Metrics struct {
	Metrics *Metrics `protobuf:"bytes,1,opt,name=metrics,proto3,oneof"`
}

type BulkRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*BulkRequest_Metrics) isBulkRequest_Payload() {}

func (*BulkRequest_Data) isBulkRequest_Payload() {}

type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_proto_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *Metrics) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_proto_metrics_proto protoreflect.FileDescriptor

const file_proto_metrics_proto_rawDesc = "" +
	"\n" +
	"\x13proto/metrics.proto\x12\ametrics\x1a\x1bgoogle/protobuf/empty.proto\"{\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x05gauge\x18\x02 \x01(\v2\x0e.metrics.GaugeH\x00R\x05gauge\x12,\n" +
	"\acounter\x18\x03 \x01(\v2\x10.metrics.CounterH\x00R\acounterB\a\n" +
	"\x05value\"\x1d\n" +
	"\x05Gauge\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"\x1f\n" +
	"\aCounter\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\x03R\x05delta\"[\n" +
	"\rMetricRequest\x12)\n" +
	"\x06metric\x18\x01 \x01(\v2\x0f.metrics.MetricH\x00R\x06metric\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"\\\n" +
	"\vBulkRequest\x12,\n" +
	"\ametrics\x18\x01 \x01(\v2\x10.metrics.MetricsH\x00R\ametrics\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"4\n" +
	"\aMetrics\x12)\n" +
	"\ametrics\x18\x01 \x03(\v2\x0f.metrics.MetricR\ametrics2\x86\x01\n" +
	"\x0eMetricsService\x128\n" +
	"\x06Update\x12\x16.metrics.MetricRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\n" +
	"BulkUpdate\x12\x14.metrics.BulkRequest\x1a\x16.google.protobuf.EmptyB\x10Z\x0einternal/protob\x06proto3"

var (
	file_proto_metrics_proto_rawDescOnce sync.Once
	file_proto_metrics_proto_rawDescData []byte
)

func file_proto_metrics_proto_rawDescGZIP() []byte {
	file_proto_metrics_proto_rawDescOnce.Do(func() {
		file_proto_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metrics_proto_rawDesc), len(file_proto_metrics_proto_rawDesc)))
	})
	return file_proto_metrics_proto_rawDescData
}

var file_proto_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_metrics_proto_goTypes = []any{
	(*Metric)(nil),        // 0: metrics.Metric
	(*Gauge)(nil),         // 1: metrics.Gauge
	(*Counter)(nil),       // 2: metrics.Counter
	(*MetricRequest)(nil), // 3: metrics.MetricRequest
	(*BulkRequest)(nil),   // 4: metrics.BulkRequest
	(*Metrics)(nil),       // 5: metrics.Metrics
	(*emptypb.Empty)(nil), // 6: google.protobuf.Empty
}
var file_proto_metrics_proto_depIdxs = []int32{
	1, // 0: metrics.Metric.gauge:type_name -> metrics.Gauge
	2, // 1: metrics.Metric.counter:type_name -> metrics.Counter
	0, // 2: metrics.MetricRequest.metric:type_name -> metrics.Metric
	5, // 3: metrics.BulkRequest.metrics:type_name -> metrics.Metrics
	0, // 4: metrics.Metrics.metrics:type_name -> metrics.Metric
	3, // 5: metrics.MetricsService.Update:input_type -> metrics.MetricRequest
	4, // 6: metrics.MetricsService.BulkUpdate:input_type -> metrics.BulkRequest
	6, // 7: metrics.MetricsService.Update:output_type -> google.protobuf.Empty
	6, // 8: metrics.MetricsService.BulkUpdate:output_type -> google.protobuf.Empty
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_metrics_proto_init() }
func file_proto_metrics_proto_init() {
	if File_proto_metrics_proto != nil {
		return
	}
	file_proto_metrics_proto_msgTypes[0].OneofWrappers = []any{
		(*Metric_Gauge)(nil),
		(*Metric_Counter)(nil),
	}
	file_proto_metrics_proto_msgTypes[3].OneofWrappers = []any{
		(*MetricRequest_Metric)(nil),
		(*MetricRequest_Data)(nil),
	}
	file_proto_metrics_proto_msgTypes[4].OneofWrappers = []any{
		(*BulkRequest_Metrics)(nil),
		(*BulkRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metrics_proto_rawDesc), len(file_proto_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metrics_proto_goTypes,
		DependencyIndexes: file_proto_metrics_proto_depIdxs,
		MessageInfos:      file_proto_metrics_proto_msgTypes,
	}.Build()
	File_proto_metrics_proto = out.File
	file_proto_metrics_proto_goTypes = nil
	file_proto_metrics_proto_depIdxs = nil
}
